# Generated by Django 4.2.17 on 2024-12-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da tag')),
                ('color_class', models.CharField(help_text='Define uma classe para colorir os elementos. Ex.: primary, secondary, etc.', max_length=20, verbose_name='Classe Bootstrap para cor')),
            ],
            options={
                'verbose_name': 'Tag de anotação',
                'verbose_name_plural': 'Tags de anotação',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.notetag'),
        ),
    ]
