# Generated by Django 4.2.17 on 2024-12-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notetag_note_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title'], 'verbose_name': 'Anotação', 'verbose_name_plural': 'Anotações'},
        ),
    ]
