# Generated by Django 4.2.17 on 2025-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='É público?'),
        ),
    ]
