# Generated by Django 4.2.17 on 2025-04-01 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_parent_folder_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_notes', to='notes.folder'),
        ),
    ]
