# Generated by Django 4.2.17 on 2024-12-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'À fazer'), ('development', 'Em desenvolvimento'), ('done', 'Finalizado')], default='backlog', max_length=100, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
