# Generated by Django 4.2.17 on 2025-01-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transactioncategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='É permanente?'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição da dívida')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total da dívida')),
                ('installment_count', models.PositiveIntegerField(verbose_name='Número de parcelas')),
                ('first_due_date', models.DateField(verbose_name='Data de vencimento da 1ª parcela')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Está quitada?')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_debts', to='finance.transactioncategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.debt'),
        ),
    ]
