# Generated by Django 4.2.17 on 2025-02-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-first_due_date'], 'verbose_name': 'Dívida', 'verbose_name_plural': 'Dívidas'},
        ),
    ]
