# Generated by Django 4.2.17 on 2025-02-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_debt_user_transaction_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='user',
            new_name='owner',
        ),
    ]
