# Generated by Django 4.2.17 on 2024-12-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAIConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.agentai')),
            ],
            options={
                'verbose_name': 'Histórico de conversa',
                'verbose_name_plural': 'Históricos de conversa',
                'ordering': ['-created_at'],
            },
        ),
    ]
